### ISSUE TITLE
Rhino Compas IGS initiation error

### ISSUE THREAD

**Issue by rstarossek** [BlockResearchGroup/compas-IGS#5]
**Describe the bug**

I first installed and worked with IGS late last year. It worked fine then. Now I am getting the following error message when trying to initiate the plugin
![image](https://user-images.githubusercontent.com/107813224/174498421-850d36ba-d6a0-40c9-9424-970bb6f2c831.png)

It is followed by following error message, when I keep rhino open and try to initiate IGS

![image](https://user-images.githubusercontent.com/107813224/174498502-3b35f212-2968-4cdf-a397-659446fb075e.png)

These errors persist after trying to reinstall IGS. Other IGS commands will give similar error messages

**To Reproduce**

1. install rhino igs following the steps described in https://blockresearchgroup.gitbook.io/igs/quick-start/untitled
2. Initiate IGS in rhino
3. Instead of the expected initiation, the error messages as seen above will pop up

**Expected behavior**

Regular initiation and working behavior of the plugin

**Computer**
- Windows 10
-rhino 7.1922165.13001,2022-06-14
-igsGS_v0.3.3rc0

**Additional context**

No python installed on machine

**Comment by rstarossek** [comment]
Update:
I also tried installing it through the compas-dashboard following the instructions from https://blockresearchgroup.gitbook.io/csd1-2021/tools/compas-tools
including installation of anaconda3. The previous plugin and script files were deleted and uninstalled previously. The compas console returns a "failed" message and following console messages:
![image](https://user-images.githubusercontent.com/107813224/175795469-31f8571a-5d59-43c3-9dcc-42db1ec97a40.png)

>>>echo __________Add conda-forge__________ && conda config --add channels conda-forge && echo __________Create compas-apps env__________ && conda create -n compas-apps -y && echo __________Activate Environment__________ && conda activate compas-apps && echo __________Install planarity and cython__________ && conda install python-planarity cython=0.29.23  -y && echo __________Install the package__________ && pip install compas_igs==v0.3.3rc0 && echo __________Install to Rhino__________ && python -m compas_igs.install --rhino_version 7.0
__________Add conda-forge__________ 
Warning: 'conda-forge' already in 'channels' list, moving to the top
__________Create compas-apps env__________ 
D:\Programs\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Collecting package metadata (current_repodata.json): ...working... 
done
Solving environment: ...working... 
done

## Package Plan ##

  environment location: D:\Programs\anaconda3\envs\compas-apps



Preparing transaction: ...working... 
done
Verifying transaction: ...working... 
done
Executing transaction: ...working... done
#
# To activate this environment, use
#
#     $ conda activate compas-apps
#
# To deactivate an active environment, use
#
#     $ conda deactivate

__________Activate Environment__________ 
__________Install planarity and cython__________ 
D:\Programs\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Collecting package metadata (current_repodata.json): ...working... 
done
Solving environment: ...working... 
failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): ...working... 
done
Solving environment: ...working... 
done

## Package Plan ##

  environment location: D:\Programs\anaconda3\envs\compas-apps

  added / updated specs:
    - cython=0.29.23
    - python-planarity


The following NEW packages will be INSTALLED:

  bzip2              conda-forge/win-64::bzip2-1.0.8-h8ffe710_4
  ca-certificates    conda-forge/win-64::ca-certificates-2022.6.15-h5b45459_0
  cython             conda-forge/win-64::cython-0.29.23-py39h415ef7b_1
  libffi             conda-forge/win-64::libffi-3.4.2-h8ffe710_5
  libzlib            conda-forge/win-64::libzlib-1.2.12-h8ffe710_1
  openssl            conda-forge/win-64::openssl-3.0.4-h8ffe710_0
  pip                conda-forge/noarch::pip-22.1.2-pyhd8ed1ab_0
  planarity          conda-forge/win-64::planarity-3.0.0.5-hfa6e2cd_1002
  python             conda-forge/win-64::python-3.9.13-hcf16a7b_0_cpython
  python-planarity   conda-forge/win-64::python-planarity-0.4.1-py39hb82d6ee_7
  python_abi         conda-forge/win-64::python_abi-3.9-2_cp39
  setuptools         conda-forge/win-64::setuptools-62.6.0-py39hcbf5309_0
  sqlite             conda-forge/win-64::sqlite-3.38.5-h8ffe710_0
  tk                 conda-forge/win-64::tk-8.6.12-h8ffe710_0
  tzdata             conda-forge/noarch::tzdata-2022a-h191b570_0
  ucrt               conda-forge/win-64::ucrt-10.0.20348.0-h57928b3_0
  vc                 conda-forge/win-64::vc-14.2-hb210afc_6
  vs2015_runtime     conda-forge/win-64::vs2015_runtime-14.29.30037-h902a5da_6
  wheel              conda-forge/noarch::wheel-0.37.1-pyhd8ed1ab_0
  xz                 conda-forge/win-64::xz-5.2.5-h62dcd97_1


Preparing transaction: ...working... 
done
Verifying transaction: ...working... 
done
Executing transaction: ...working... 
done
__________Install the package__________ 
Collecting compas_igs==v0.3.3rc0
  Using cached compas_igs-0.3.3rc0-py2.py3-none-any.whl (1.9 MB)
Collecting compas-ags
  Using cached compas_ags-1.1.1-py2.py3-none-any.whl (31 kB)
Collecting compas>=1.9.4
  Using cached COMPAS-1.16.0-py2.py3-none-any.whl (5.2 MB)
Collecting pillow
  Using cached Pillow-9.1.1-cp39-cp39-win_amd64.whl (3.3 MB)
Collecting pycollada
  Using cached pycollada-0.7.2-py3-none-any.whl
Collecting schema
  Using cached schema-0.7.5-py2.py3-none-any.whl (17 kB)
Collecting sympy
  Using cached sympy-1.10.1-py3-none-any.whl (6.4 MB)
Requirement already satisfied: cython in d:\programs\anaconda3\envs\compas-apps\lib\site-packages (from compas>=1.9.4->compas_igs==v0.3.3rc0) (0.29.23)
Collecting scipy>=1.1
  Using cached scipy-1.8.1-cp39-cp39-win_amd64.whl (36.9 MB)
Collecting matplotlib>=3.1
  Using cached matplotlib-3.5.2-cp39-cp39-win_amd64.whl (7.2 MB)
Collecting numpy>=1.15.4
  Using cached numpy-1.23.0-cp39-cp39-win_amd64.whl (14.7 MB)
Collecting typing-extensions
  Using cached typing_extensions-4.2.0-py3-none-any.whl (24 kB)
Collecting watchdog
  Using cached watchdog-2.1.9-py3-none-win_amd64.whl (78 kB)
Collecting networkx
  Using cached networkx-2.8.4-py3-none-any.whl (2.0 MB)
Collecting jsonschema
  Using cached jsonschema-4.6.0-py3-none-any.whl (80 kB)
Collecting imageio>=2.7
  Using cached imageio-2.19.3-py3-none-any.whl (3.4 MB)
Collecting fonttools>=4.22.0
  Using cached fonttools-4.33.3-py3-none-any.whl (930 kB)
Collecting cycler>=0.10
  Using cached cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting python-dateutil>=2.7
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.4.3-cp39-cp39-win_amd64.whl (55 kB)
Collecting pyparsing>=2.2.1
  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)
Collecting packaging>=20.0
  Using cached packaging-21.3-py3-none-any.whl (40 kB)
Collecting attrs>=17.4.0
  Using cached attrs-21.4.0-py2.py3-none-any.whl (60 kB)
Collecting pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0
  Using cached pyrsistent-0.18.1-cp39-cp39-win_amd64.whl (61 kB)
Collecting contextlib2>=0.5.5
  Using cached contextlib2-21.6.0-py2.py3-none-any.whl (13 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.2.1-py3-none-any.whl (532 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: mpmath, watchdog, typing-extensions, sympy, six, pyrsistent, pyparsing, pillow, numpy, networkx, kiwisolver, fonttools, cycler, contextlib2, attrs, scipy, schema, python-dateutil, packaging, jsonschema, imageio, pycollada, matplotlib, compas, compas-ags, compas_igs
Successfully installed attrs-21.4.0 compas-1.16.0 compas-ags-1.1.1 compas_igs-0.3.3rc0 contextlib2-21.6.0 cycler-0.11.0 fonttools-4.33.3 imageio-2.19.3 jsonschema-4.6.0 kiwisolver-1.4.3 matplotlib-3.5.2 mpmath-1.2.1 networkx-2.8.4 numpy-1.23.0 packaging-21.3 pillow-9.1.1 pycollada-0.7.2 pyparsing-3.0.9 pyrsistent-0.18.1 python-dateutil-2.8.2 schema-0.7.5 scipy-1.8.1 six-1.16.0 sympy-1.10.1 typing-extensions-4.2.0 watchdog-2.1.9
__________Install to Rhino__________ 
Traceback (most recent call last):
  File "D:\Programs\anaconda3\envs\compas-apps\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programs\anaconda3\envs\compas-apps\lib\runpy.py", line 87, in _run_code

 ---------- Checking packages ----------
   compas               OK
   compas_rhino         OK
   compas_ags           OK
   compas_igs           OK
compas_igs is editable install:  False

 ---------- Installing compas_ags python plugin ----------
    exec(code, run_globals)
  File "D:\Programs\anaconda3\envs\compas-apps\lib\site-packages\compas_igs\install.py", line 72, in <module>
    python_plugins_path = compas_rhino._get_python_plugins_path(args.rhino_version)
AttributeError: module 'compas_rhino' has no attribute '_get_python_plugins_path'
Error: Command failed: D:\Programs\anaconda3/Scripts/activate.bat && echo __________Add conda-forge__________ && conda config --add channels conda-forge && echo __________Create compas-apps env__________ && conda create -n compas-apps -y && echo __________Activate Environment__________ && conda activate compas-apps && echo __________Install planarity and cython__________ && conda install python-planarity cython=0.29.23  -y && echo __________Install the package__________ && pip install compas_igs==v0.3.3rc0 && echo __________Install to Rhino__________ && python -m compas_igs.install --rhino_version 7.0
Warning: 'conda-forge' already in 'channels' list, moving to the top
D:\Programs\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
D:\Programs\anaconda3\lib\site-packages\requests\__init__.py:109: RequestsDependencyWarning: urllib3 (1.26.9) or chardet (5.0.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn(
Traceback (most recent call last):
  File "D:\Programs\anaconda3\envs\compas-apps\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programs\anaconda3\envs\compas-apps\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Programs\anaconda3\envs\compas-apps\lib\site-packages\compas_igs\install.py", line 72, in <module>
    python_plugins_path = compas_rhino._get_python_plugins_path(args.rhino_version)
AttributeError: module 'compas_rhino' has no attribute '_get_python_plugins_path'

**Comment by Licini** [comment]
Hi @rstarossek installation through dashboard could be impacted by some latest compas updates and not working properly at the moment. This might be a redundant question, but have you tried to re-install IGS directly through installer at https://github.com/BlockResearchGroup/compas-IGS/releases/tag/v0.3.3rc0 ? (This is a compiled version that suppose to always work). If the same error presents, could you in Rhino python editor run the script:
```python
import compas
print compas.__version__
```
and let me know what compas version is it in your Rhino environment?

**Comment by rstarossek** [comment]
Hi @Licini thanks for your response. I tried reinstalling through the stand-alone installer before, but gave it another go, since I also reinstalled rhino in the last few days as well. Unfortunately, I am still getting the same error. 

I ran the script you posted and the output/version seems to be 1.11.1

![image](https://user-images.githubusercontent.com/107813224/176339661-ac0497e8-a091-4c8c-a2ec-8d5411b7d9d0.png)

Let me know if I should try anything else or if you need any other information

**Comment by Licini** [comment]
Hi @rstarossek Thanks for the feedback. We have pin-pointed the issue now. These errors were originated from a Rhino version update earlier this year which affects how the Ironpython environment can be detected programmatically. COMPAS itself been patched to address the issue in February, however it also has introduced numerous other changes which COMPAS-IGS hasn't been caught up yet. To bring everything up to date we might need a bit longer especially the main author of IGS @ricardoavelino is currently on vacation. Meanwhile the easiest way to fix the issue would be downgrade to an earlier version of Rhino7 such as SR9: https://drive.google.com/file/d/1P0fBmx--9SlkANn3Q-cUiXYORtv6eNel/view?usp=sharing (you will need to first uninstall your current rhino before using the installer)

**Comment by rstarossek** [comment]
Hi @Licini , I reinstalled as per instructions and the plugin works again! Will keep in mind not to update my rhino for a while ;) Thank you very much for your help, and I am looking forward to further updates to the plugin!

**Comment by maximilion83** [comment]
Hi @Licini may I know if this problem has been fixed? cause I am currently having the same problem now and was wondering if there are any other fix other than downgrading to an earlier version?
